apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: tickets-mongo-depl
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: tickets-mongo
      template:
        metadata:
          labels:
            app: tickets-mongo
        spec:
          containers:
            - name: tickets-mongo
              image: mongo
              imagePullPolicy: Always
  - apiVersion: v1
    kind: Service
    metadata:
      name: tickets-mongo-srv
    spec:
      selector:
        app: tickets-mongo
      ports:
        - port: 27017
          targetPort: 27017
          protocol: TCP
          name: auth-mongo-port